name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application jar
      working-directory: ./RESTFul-API-Implementacao/restful-api-implementacao
      run: mvn clean package
  
    - name: Docker Compose Build
      working-directory: ./RESTFul-API-Implementacao
      run: docker compose build
      
    - name: Push to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/restful-api-implementacao:latest ${{ secrets.DOCKER_USERNAME }}/restful-api-implementacao:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/restful-api-implementacao:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/restful-api-implementacao:latest
